spring:
  application:
    name: tg-webhook-bot-core
  profiles:
    active: dev
server:
  port: 9090
logging:
  logback:
    rollingpolicy:
      max-history: 180
      max-file-size: 1GB
  pattern:
    console: "%d{yyyy-MM-dd E HH:mm:ss.SSS} %clr(%-5p) %clr(${PID}){blue} --- [%t] %clr(%logger.%M.%L){cyan} : %msg%n"
    file: "%d{yyyy-MM-dd E HH:mm:ss.SSS} %clr(%-5p) %clr(${PID}){blue} --- [%t] %clr(%logger.%M.%L){cyan} : %msg%n"


  file:
    name: ./logs/${spring.application.name}-${spring.profiles.active}.log